package de.jkamue.mqtt.encoder.connack

enum class ConnackPropertyIdentifier(val identifier: Int) {
    SESSION_EXPIRY_INTERVAL(17),
    RECEIVE_MAXIMUM(33),
    MAXIMUM_QOS(36),
    RETAIN_AVAILABLE(37),
    MAXIMUM_PACKET_SIZE(39),
    ASSIGNED_CLIENT_IDENTIFIER(18),
    TOPIC_ALIAS_MAXIMUM(34),
    REASON_STRING(31),
    USER_PROPERTY(38),
    WILDCARD_SUBSCRIPTION_AVAILABLE(11),
    SUBSCRIPTION_IDENTIFIERS_AVAILABLE(41),
    SHARED_SUBSCRIPTION_AVAILABLE(42),
    SERVER_KEEP_ALIVE(19),
    RESPONSE_INFORMATION(26),
    SERVER_REFERENCE(28),
    AUTHENTICATION_METHOD(21),
    AUTHENTICATION_DATA(22)
}